### ISSUE TITLE
Error: Dictionary has invalid data in '0'

### ISSUE THREAD

**Issue by Ciana1220** [MarvNC/kanjidego-yomitan-anki#1]
Hello,
I tried to import the dictionary and got this error

![errotítulo](https://github.com/MarvNC/kanjidego-yomitan-anki/assets/122986073/e83b66f0-1fd5-4c17-a054-e54292ff02cc)

**Comment by MarvNC** [comment]
Hi, what version of Yomitan are you using? Can you share information from your info screen? It's possible that there are issues with older versions of Yomi(chan/baba), I haven't tested it with those.

**Comment by Ciana1220** [comment]
Yomitan Info:

![info](https://github.com/MarvNC/kanjidego-yomitan-anki/assets/122986073/dd5f2b14-58ef-4893-8fec-b6d981621d2a)

**Comment by MarvNC** [comment]
I'm not sure if there are any issues with old versions that would affect this dictionary, but can you try updating to the latest Yomitan and see if that helps? Currently it's on [2024.01.14.0](https://github.com/themoeway/yomitan/releases/tag/24.01.14.0).

**Comment by Ciana1220** [comment]
Hello, I updated and it seems to be working fine. Thank you very much.

**Comment by MarvNC** [comment]
Glad to see it's working and thanks for the report, I'll add a note about updating Yomitan.
